apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
     app: client
spec:
  containers:
  - name: example-workload
    image: ppatel1989/spiffe-csi-driver-example-workload:example
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    env:
    - name: SPIFFE_ENDPOINT_SOCKET
      value: unix:///spiffe-workload-api/spire-agent.sock
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: spiffe-workload-api
    csi:
      driver: "csi.spiffe.io"
